add first commit
BI-kotlin-in-action/JoSeungBin-Project-HW pull request #1
Opened 2023-11-06 12:46 UTC by vkflco08

2023-11-06 15:12 UTC, konempty requested changes
크 고생하셨습니다 👍 👍 
조금만더 수정 부탁 드리구요
PR제목이 PR의 내용을 잘 설명해주지 못하는것 같은데
좀더 직관적으로 지어주시구요 PR description도 채워주시면 좋을것 같습니다~!

2023-11-06 15:12 UTC, konempty commented on LottoAssignment/LottoAssignment.iml
> +</module>
ㄷㄷㄷ 불필요한 파일까지 전부 올라왔네요 깃 이그노어로 불필요한 파일은 올라오지 않도록 처리 부탁드릴게요..!
https://www.toptal.com/developers/gitignore/api/intellij+iml,windows
요 링크에 있는 정보들을 깃이그노어 파일에 넣으시면 됩니다

2023-11-06 15:12 UTC, konempty commented on LottoAssignment/src/main/kotlin/READ_ME.txt
> +7. 일급 컬렉션으로 여러가지 컬렉션을 래핑해보고 객체사이의 협력관계를 만들어본다
리드미 파일은 형식이 정해져 있어서 파일 형식을 맞춰주지 않으면 깃헙에서 인식이 되지 않습니다..!
파일 형식을 README.md로 바꿔주세요 ㅎㅎ

2023-11-06 15:12 UTC, konempty commented on LottoAssignment/src/main/kotlin/LottoTickets.kt
> +}
이렇게 클래스에 속해 있지 않은 함수들은 지양해주세요!
요 함수들을 적절한 클래스로 묶어주시면 됩니다~!

2023-11-06 15:12 UTC, konempty commented on LottoAssignment/src/main/kotlin/LottoTickets.kt
> +    tickets.addTicket(List(6) { Random.nextInt(1, 46) }.distinct().sorted())
distinct()를 하게되면 중복이 있었을 경우 List의 사이즈가 6미만으로 될수도 있습니다..!
중복 제거를 해도 한개의 로또에서는 6개의 숫자가 있도록 수정해주세요 ㅎㅎ
ex) 1,2,3,4,4,5 -> 1,2,3,4,5

2023-11-06 15:12 UTC, konempty commented on LottoAssignment/src/main/kotlin/Tickets.kt
> +    private var ticketNum = num
티켓의 개수는 변하지 않는데 var로 하신이유가 있을까요??

2023-11-06 15:12 UTC, konempty commented on LottoAssignment/src/main/kotlin/Tickets.kt
> +    private var cost = cost
cost도 마찬가지로 이유가 있는지 궁금합니다!

2023-11-06 15:12 UTC, konempty commented on LottoAssignment/src/main/kotlin/WinningTicket.kt
> +    private val winningTickets = List<Int>(6) { Random.nextInt(1, 46) }.distinct().sorted()
당첨 로또 생성하는 로직이 자동로또를 생성하는 로직과 동일한데 두개를 통일시킬 방법은 없을까요??

2023-11-06 15:12 UTC, konempty commented on LottoAssignment/src/main/kotlin/WinningTicket.kt
> +    fun getTicket(): List<Int> = winningTickets
winningTickets를 private로 숨기면서 getter를 따로 만들어 주는 이유가 궁금합니다!

2023-11-06 15:12 UTC, konempty commented on LottoAssignment/src/main/kotlin/Main.kt
> +        val sum = 0
요건 사용되지 않는 변수 같은데 총합 계산하는 로직을 빠트리신걸까요??

2023-11-06 15:12 UTC, konempty commented on LottoAssignment/src/main/kotlin/LottoTickets.kt
> +fun manualTicket(tickets: LottoTickets) {
지금보니까 관계가 역전이 된것 같은데
LottoTickets가 더 넓은 도메인인데 한개의 로또를 생성하기 위해 생성한 모든 로또를 넘겨줘야 한다는건 뭔가 어색하네요 ㅋㅋㅋ...
요 함수가 로또를 생성해서 반환해주면 외부에서 받아서 LottoTickets에 넣어주는 방식으로 하면 좋을것 같아요!

2023-11-07 09:13 UTC, vkflco08 commented on LottoAssignment/src/main/kotlin/WinningTicket.kt
> +    private val winningTickets = List<Int>(6) { Random.nextInt(1, 46) }.distinct().sorted()
Main.kt에 숫자를 만드는 함수를 만들어서 호출하는 방법으로 하면 이상할까요...?

2023-11-07 13:39 UTC, konempty commented on LottoAssignment/src/main/kotlin/WinningTicket.kt
> +    private val winningTickets = List<Int>(6) { Random.nextInt(1, 46) }.distinct().sorted()
그것도 괜찮을수도 있는데 아예 숫자만을 생성해내는 
LottoNumberGenerator 같은게 있으면 어떨까요?? ㅋㅋㅋ

2023-11-07 15:50 UTC, vkflco08 commented on LottoAssignment/src/main/kotlin/Tickets.kt
> +    private var ticketNum = num
선택사항5번 해보려다가 안바꾼것 같습니다...

2023-11-08 06:27 UTC, closed without merging

2023-11-08 06:30 UTC, vkflco08 commented
수정 완료했습니다