MENTORING-T-73 로또 프로그램
BI-kotlin-in-action/JoSeungBin-Project-HW pull request #3
Opened 2023-11-11 07:43 UTC by vkflco08

요구사항 3번 적용해서 해봤는데 맞는지 잘 모르겠습니다.

3. 각 코드의 역할과 도메인에 따라 파일 혹은 패키지를 분리해본다

2023-11-11 13:45 UTC, konempty requested changes
크 고생하셨습니다!! 👍 
조금 개선포인트가 보이는데
조금만 더 수정 부탁드릴게요~!

2023-11-11 13:45 UTC, konempty commented on .idea/vcs.xml
> +</project>
.idea 깃 이그노어 처리 해서하위 파일들도 올라오지 않도록 수정 부탁드릴게요~!

2023-11-11 13:45 UTC, konempty commented on LottoAssignmentProject.iml
> +</module>
.iml 파일도 올라오지 않도록 수정 부탁드리구요!

2023-11-11 13:45 UTC, konempty commented on JoSeungBin-Project-HW
이 레포는 일부로 연결 해두신걸까요??

2023-11-11 13:45 UTC, konempty commented on src/main/kotlin/BuyTickets.kt
> +                else -> tickets.ticketList.add(lottoNumberGenerator.makeLottoNumber())
케이스가 두개인경우 굳이 when을 쓰는것 보다 if-else를 쓰는게 좋아요!

2023-11-11 13:45 UTC, konempty commented on src/main/kotlin/BuyTickets.kt
> +        val ticket = readln().split(" ").map { it.toInt() }.sorted()
요 프로젝트에서 나눌만한 3가지 패키지을 알려드릴게요!

도메인 : 단순히 정보를 가지고 패키지 간의 정보 전달을 위해 사용되는 클래스 모음
뷰 : IO에 관련된 모든 로직을 수행하는 클래스 모음
컨트롤러 : 뷰와 도메인을 받아들여 프로그램의 전체과정을 컨트롤하는 역할

따라서 요 코드는 뷰에서 해야하는 역할/책임 일것 같아요!

그리고 BuyTickets는 컨트롤러이자 뷰이자 도메인 같아 보여요..!

2023-11-11 13:45 UTC, konempty commented on src/main/kotlin/BuyTickets.kt
> +class BuyTickets() {
지금 봤는데 클래스명이 동사로 시작하는 경우는 흔치않아요!
가능하면 명사로 지어주세요

2023-11-11 13:45 UTC, konempty commented on src/main/kotlin/LottoNumberGenerator.kt
> +        while (numbers.size < 6) {
숫자가 중복이 되면 안된다, 소팅이 되어야 한다 라는
요구조건을 만족하기위해선 SET이 좋은데
set도 종류가 여러개니까 어떤 set이 좋을지는 찾아서 적용 부탁드려요~!

2023-11-11 13:45 UTC, konempty commented on src/main/kotlin/LottoNumberGenerator.kt
> +            val randomNumber = Random.nextInt(1, 46)
1과 46은 상수화를 하면 좋을것 같구요
46보다는 45가 더 의미있는 숫자일것 같아서 아래와 같이 45을 쓰도록 하는 코드로 바꾸면 좋을것 같아요!

`    print(IntArray(1000) { Random.nextInt(1..45) }.max())`

2023-11-11 13:45 UTC, konempty commented on src/main/kotlin/LottoTickets.kt
> +<<<<<<< HEAD
???

2023-11-11 13:45 UTC, konempty commented on src/main/kotlin/LottoTickets.kt
> +    private val tickets = mutableListOf<List<Int>>()
List<Int>를 로또한장을 의미하는 일급컬렉션으로 만들면 좋을것 같아요!

2023-11-11 13:45 UTC, konempty commented on src/main/kotlin/LottoTickets.kt
> +            println(tickets[i])
저라면 for문 대신
```kotlin
fun printTicket() {
    tickets.joinToString("\n")
}
```
요렇게 한줄로 처리할것 같아요!

2023-11-11 13:45 UTC, konempty commented on src/main/kotlin/LottoTickets.kt
> +        addTicket(ticket)
요것도 뷰의 역할이겠네요 ㅎㅎ

2023-11-11 13:45 UTC, konempty commented on src/main/kotlin/LottoTickets.kt
> +>>>>>>> b19235a (MENTORING-T-73 로또 프로그램 수정 #1.2)
??? 뭔가 이상하네요
전체적으로 코드 한번 확인해주세요!

2023-11-11 13:45 UTC, konempty commented on src/main/kotlin/WinningTicket.kt
> +            val sum = 0
이 변수는 아직도 안쓰이고있네요 ㅋㅋㅋㅋ

2023-11-11 13:45 UTC, konempty commented on src/main/kotlin/WinningTicket.kt
> +                3 -> println("${tickets.ticketList[i]} | 5KW 당첨")
몇개 맞췄을때 몇등이며 상금은 얼마다 라는걸 명시해둔 enum으로 관리하면 좋을것 같아요!

2023-11-11 13:45 UTC, konempty commented on .gitignore
> +.DS_Store
<img width="210" alt="스크린샷 2023-11-11 오후 10 44 03" src="https://github.com/BI-kotlin-in-action/JoSeungBin-Project-HW/assets/44064530/8c674a24-ec8d-4596-bd66-66c9e70b2232">

파일끝에 개행이 없다면 깃헙에서도 경고를 띄워주고
파일끝 개행은 일부 시스템에서는 없으면 에러를 일으킵니다..!
아래 URL을 확인해서 적용해주세요!

https://velog.io/@d-h-k/intellij-%ED%8C%8C%EC%9D%BC%EB%81%9D%EC%97%90-%EA%B0%9C%ED%96%89%EC%9D%84-%EC%9E%90%EB%8F%99%EC%9C%BC%EB%A1%9C-%EC%B6%94%EA%B0%80%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95

2023-11-13 09:48 UTC, vkflco08 commented
LottoTickets에서 일급 컬렉션 어떻게 사용하는지 잘 모르겠습니다

2023-11-13 10:11 UTC, konempty requested changes
코드가 많이 좋아진것 같아요! 
조금만더 수정부탁드릴게요~!

2023-11-13 10:11 UTC, konempty commented on .idea/ktlint.xml
.idea 폴더 내용들이 아직 남아 있네요 ㅠㅠ
깃이그노어 처리하고 이미 올라간 파일들을 지워주는 작업까지 해야 하는데 아래 링크를 참고해주세요
https://devjeonblog.oopy.io/3d13207f-b830-4bbc-9d35-bd6dbfc824f0

2023-11-13 10:11 UTC, konempty commented on src/main/kotlin/Main.kt
> +    winTickets.calculateWinningTickets(tickets, winTickets)
모든 코드들은 컨트롤러 안에 속해 있어야 하는데 이 코드들은 컨트롤러를 벗어났네요
베스트 프랙티스는 아래 인규님 프로젝트에서 잘 드러납니다!
https://github.com/BI-kotlin-in-action/InGyuMoon-lotto/blob/a73f5bf3ed67a3974a66d6baf2c1f22931b047aa/src/main/kotlin/Main.kt

2023-11-13 10:11 UTC, konempty commented on src/main/kotlin/WinningTicket.kt
> +                3 -> WinningPrize.FOURTH.prize
맞은 개수에 대해 enum값을 반환하는건 WinningPrize의 역할일것 같아요!
val result = WinningPrize.getPrize(count)
요런 코드가 가능하도록 수정해주세요~!

2023-11-13 10:11 UTC, konempty commented on src/main/kotlin/view/LottoView.kt
> +    val lottoTickets = LottoTickets(lottoNum, cost)
입력만 받는게 view의 역할이구요 
입력 받은 내용을 컨트롤러에게 넘겨서 도메인 객체를 생성하시는 패턴이 좋습니다~!

2023-11-13 10:11 UTC, konempty commented on src/main/kotlin/LottoTickets.kt
> +    public val ticketList = mutableSetOf<Set<Int>>()
<img width="538" alt="스크린샷 2023-11-13 오후 7 06 23" src="https://github.com/BI-kotlin-in-action/JoSeungBin-Project-HW/assets/44064530/df7177e0-1efb-43ff-9883-2d8b649aa2a2">

요 리뷰를 빠트리셨네요 ㅎㅎ

2023-11-13 10:11 UTC, konempty commented on src/main/kotlin/LottoTickets.kt
> +    public val cost = cost
요 두개를 차라리 초기화 하면서 프로퍼티로 받았다면 어땠을까요??
```kotlin
class LottoTickets(val ticketNum: Int, val cost: Int) 
```

2023-11-13 10:11 UTC, konempty commented on src/main/kotlin/LottoNumberGenerator.kt
> +            val randomNumber = Random.nextInt(MINIMUM_NUM..MAXIMUM_NUM)
요건 코멘트는 아니고 단순 제안인데
중복 없이 숫자를 뽑는 로직은 셔플링과 subList를 사용하는거예요!
ex)
1, 2, 3, 4, 5, 6의 숫자 배열에서 중복없이 3개를 뽑으려면
셔플링 후(2, 6, 3, 4, 5, 1)
앞에서 부터 3개 추출 (2, 6, 3)

2023-11-13 10:11 UTC, konempty commented on src/main/kotlin/view/LottoView.kt
> +    val lottoNum = cost / 1000
1000이라는 매직 넘버도 상수화를 하면 좋을것 같아요!

2023-11-13 10:11 UTC, konempty commented on src/main/kotlin/LottoNumberGenerator.kt
> +        const val MAXIMUM_NUM = 45
다른곳에서 쓰지 않는다면 private로 선언하면 좋을것 같아요!

2023-11-13 10:11 UTC, konempty commented on src/main/kotlin/CreateTickets.kt
> +    val lottoNumberGenerator = LottoNumberGenerator()
어떤 클래스에도 속하지 않은 전역 함수를 쓰는건 좋지 않아요 ㅠㅠ
클래스에 속하는 메소드로 바꿔주세요

2023-11-14 12:22 UTC, vkflco08 commented on src/main/kotlin/LottoTickets.kt
> +    public val ticketList = mutableSetOf<Set<Int>>()
일급컬렉션 어떻게 만드는지 잘 모르겠습니다...

2023-11-15 11:17 UTC, konempty requested changes
이전에 리뷰 드린 내용이 하나도 반영이 안됐네요 ㅠㅠ

2023-11-16 00:44 UTC, konempty requested changes
고생이 많으시네요 ㅋㅋ큐ㅠㅠ
진짜 조금만더 수정부탁드릴게요!

2023-11-16 00:44 UTC, konempty commented on src/main/kotlin/CreateTickets.kt
> +class CreateTickets {
아핫 ㅋㅋㅋ... 이전에 드렸던 리뷰인
>  클래스명이 동사로 시작하는 경우는 흔치않아요!

를 다시 적용해주세요!

2023-11-16 00:44 UTC, konempty commented on src/main/kotlin/CreateTickets.kt
> +        val lottoView = LottoView()
뷰는 컨트롤러에서 선언되어야해요!
그리고 가능하면 프로그램에서 유일하게 생성되어야 하구요

2023-11-16 00:44 UTC, konempty commented on src/main/kotlin/LottoTickets.kt
> +    val ticketList = mutableSetOf<Set<Int>>()
가변성 노출을 최소화 하기위해 private로 숨기면 좋을것 같아요!

2023-11-16 00:44 UTC, konempty commented on src/main/kotlin/LottoTickets.kt
> +        println(ticketList.joinToString("\n"))
화면에 출력하는 역할은 도메인의 역할이 아닌 뷰의 역할이예요!

2023-11-16 00:44 UTC, konempty commented on src/main/kotlin/WinningPrize.kt
> +        fun getRank(matchNum: Int): WinningPrize {
이전 강의때 말씀드린대로 \@JvmStatic을 붙여야 자바의 static에 대응하는 코드를 만들수 있어요

2023-11-16 00:44 UTC, konempty commented on src/main/kotlin/WinningTicket.kt
> +    private val winningTicket = lottoNumberGenerator.makeLottoNumber()
다른 로또들 처럼 외부에서 번호를 생성해서 해당 번호를 주입받아 생성하는게 좋을것 같아요!
lottoNumberGenerator까지 요 도메인이 가지고 있는건 너무 많은 역할을 주는것 같아요 ㅠㅠ

2023-11-16 00:44 UTC, konempty commented on src/main/kotlin/WinningTicket.kt
> +                println("${tickets.ticketList.elementAt(i)} | ${result.prize} KW 당첨")
요기 화면에 출력하는 로직도 뷰의 역할일것 같아요!

2023-11-16 00:44 UTC, konempty commented on src/main/kotlin/WinningTicket.kt
> +            val count = tickets.ticketList.elementAt(i).intersect(winTickets.winningTicket.toSet()).count()
winningTicket의 자료형이 이미 set인것 같은데 다시 toSet을 해주는 이유가 있을까요??

2023-11-16 09:34 UTC, konempty requested changes
찐막..! 조금만더 수정 부탁드릴게요

2023-11-16 09:34 UTC, konempty commented on src/main/kotlin/LottoNumberGenerator.kt
> +        val numbers: TreeSet<Int> = sortedSetOf()
그러고 보니까 여기에 TreeSet이라고 명시해둔 이유가 있을까요??

2023-11-16 09:34 UTC, konempty commented on src/main/kotlin/LottoTickets.kt
> +    fun getTicket(): MutableSet<Set<Int>> {
이렇게 가변성을 노출할거라면 ticketList를 private로 숨긴 이유가 없을것 같아요 ㅠㅠ
Set<Set<Int>>이라고 해도 될것 같아요

2023-11-16 09:34 UTC, konempty commented on src/main/kotlin/LottoTickets.kt
> +    private val ticketList = mutableSetOf<Set<Int>>()
그러고 보니 mutableListOf<Set<Int>>()
요렇게 해도 되지 않을까요??
요렇게 하면 똑같은 로또를 두번 구매 못하는 이슈가 있을것 같아요

2023-11-16 09:34 UTC, konempty commented on src/main/kotlin/WinningTicket.kt
> +            val count = tickets.getTicket().elementAt(i).intersect(winningTicket).count()
i를 tickets.getTicket().elementAt(i)로만 사용한다면
for(ticket in tickets.getTicket()){
    val count =  ticket.intersect(winningTicket).count()
... 중략
}

요렇게도 가능할것 같아요~!

2023-11-16 09:34 UTC, konempty commented on src/main/kotlin/WinningTicket.kt
> +                lottoView.printWinningTicket(tickets.getTicket().elementAt(i), result.prize)
> 6. 로또의 당첨은 아래와 같으며 마지막에 사용자가 구매한 총 로또의 당첨금을 출력하시면 됩니다.

요구사항 6번이 만족이 안됐네요 ㅠㅠ
총 당첨금액을 알려주셔야 해요

2023-11-16 10:26 UTC, vkflco08 commented on src/main/kotlin/LottoNumberGenerator.kt
> +        val numbers: TreeSet<Int> = sortedSetOf()
TreeSet을 하면 정렬이 된다고 해서 썼는데, mutableListOf<Set<Int>>() 로 바꾸고 로또 번호를 입력할 때 정렬해서 넣는게 좋을까요?

2023-11-16 11:32 UTC, konempty commented on src/main/kotlin/LottoNumberGenerator.kt
> +        val numbers: TreeSet<Int> = sortedSetOf()
val numbers: SortedSet<Int> = sortedSetOf()

개취인데 요렇게 쓰는게 더 직관적이라고 생각했어요 ㅋㅋㅋ

2023-11-16 11:44 UTC, konempty approved these changes
찐막이라고 했으니까 약속은 지켜야죠! ㅋㅋㅋ
너무 고생 많으셨어요
이제 코멘트만 확인하시고 머지하셔도 좋습니다~!

2023-11-16 11:44 UTC, konempty commented on src/main/kotlin/WinningTicket.kt
> +        return sum
개취인데 저라면
```kotlin
var sum = tickets.getTicket().sumOf{ ticket ->
            val count = ticket.intersect(winningTicket).count()
            val result = WinningPrize.getRank(count)
            if(result != WinningPrize.NONE) {
                result.prize
            } else {
                0
            }
        }
        return sum
```

요렇게 했을것 같아요!

2023-11-16 11:56 UTC, merged